//! Command Generator Trait and Implementations
//!
//! This module provides an abstraction layer for command generation,
//! decoupling the generation logic from LLM clients and enabling
//! multiple generation strategies (LLM, rules, templates).
//!
//! # Architecture
//!
//! ```text
//! CommandGenerator (trait)
//!     ├── LlmCommandGenerator (uses LlmClient)
//!     ├── RuleCommandGenerator (pattern matching)
//!     └── CompositeGenerator (chain of responsibility)
//! ```
//!
//! # Usage
//!
//! ```rust,ignore
//! let generator = CompositeGenerator::new(vec![
//!     Box::new(RuleCommandGenerator::new()),
//!     Box::new(LlmCommandGenerator::new(client)),
//! ]);
//! let cmd = generator.generate(tool, docs, skill, request, config).await?;
//! ```

use crate::config::Config;
use crate::error::Result;
use crate::llm::LlmClient;
use crate::skill::Skill;
use async_trait::async_trait;
use serde::{Deserialize, Serialize};

// ────────────────────────────────────────────────────────────────────────────
// Core Types
// ────────────────────────────────────────────────────────────────────────────

/// Command generation result with metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[allow(dead_code)]
pub struct GeneratedCommand {
    /// The command arguments (e.g., "sort -@ 8 -o sorted.bam input.bam")
    pub args: String,
    /// Human-readable explanation of what the command does
    pub explanation: String,
    /// Confidence score (0.0 = uncertain, 1.0 = highly confident)
    pub confidence: f32,
    /// Source of the generated command
    pub source: CommandSource,
}

/// Source of a generated command.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[allow(dead_code)]
pub enum CommandSource {
    /// Generated by LLM API
    Llm { model: String, cache_hit: bool },
    /// Generated by rule matching
    Rule { rule_id: String },
    /// Generated from a template
    Template { template_id: String },
}

#[allow(dead_code)]
impl CommandSource {
    /// Returns a human-readable name of the source.
    pub fn name(&self) -> &str {
        match self {
            CommandSource::Llm { .. } => "llm",
            CommandSource::Rule { .. } => "rule",
            CommandSource::Template { .. } => "template",
        }
    }
}

// ────────────────────────────────────────────────────────────────────────────
// CommandGenerator Trait
// ────────────────────────────────────────────────────────────────────────────

/// Trait for command generation strategies.
///
/// Implementations can use different approaches:
/// - LLM-based generation (primary)
/// - Rule-based matching (fast path)
/// - Template instantiation (standard workflows)
#[async_trait]
#[allow(dead_code)]
pub trait CommandGenerator: Send + Sync {
    /// Generate a command from the given context.
    ///
    /// # Arguments
    ///
    /// * `tool` - Tool name (e.g., "samtools", "bwa")
    /// * `docs` - Tool documentation (from `--help` or cached)
    /// * `skill` - Optional skill file with examples
    /// * `user_request` - Natural language description of the task
    /// * `config` - Global configuration
    ///
    /// # Returns
    ///
    /// Returns a `GeneratedCommand` with args, explanation, confidence, and source.
    async fn generate(
        &self,
        tool: &str,
        docs: &str,
        skill: Option<&Skill>,
        user_request: &str,
        config: &Config,
    ) -> Result<GeneratedCommand>;

    /// Returns the name of this generator (for logging and debugging).
    fn name(&self) -> &str;
}

// ────────────────────────────────────────────────────────────────────────────
// LLM Command Generator
// ────────────────────────────────────────────────────────────────────────────

/// LLM-based command generator.
///
/// This is the primary generator that uses LLM API to generate commands
/// from natural language descriptions.
#[allow(dead_code)]
pub struct LlmCommandGenerator {
    client: LlmClient,
}

#[allow(dead_code)]
impl LlmCommandGenerator {
    /// Creates a new LLM command generator.
    pub fn new(client: LlmClient) -> Self {
        Self { client }
    }
}

#[async_trait]
impl CommandGenerator for LlmCommandGenerator {
    async fn generate(
        &self,
        tool: &str,
        docs: &str,
        skill: Option<&Skill>,
        user_request: &str,
        _config: &Config,
    ) -> Result<GeneratedCommand> {
        // Use the existing LlmClient to generate command
        let suggestion = self
            .client
            .suggest_command(tool, docs, user_request, skill, false, None)
            .await?;

        // Convert LlmCommandSuggestion to GeneratedCommand
        Ok(GeneratedCommand {
            args: suggestion.args.join(" "),
            explanation: suggestion.explanation,
            confidence: 0.85, // LLM-generated commands have moderate-high confidence
            source: CommandSource::Llm {
                model: self.client.config.effective_model(),
                cache_hit: suggestion.inference_ms == 0.0,
            },
        })
    }

    fn name(&self) -> &str {
        "llm"
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Rule Command Generator
// ────────────────────────────────────────────────────────────────────────────

/// Rule-based command generator for simple, deterministic commands.
///
/// This generator uses pattern matching to generate commands for
/// common operations without calling the LLM.
#[allow(dead_code)]
pub struct RuleCommandGenerator {
    rules: Vec<CommandRule>,
}

/// A single command generation rule.
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct CommandRule {
    /// Rule identifier
    pub id: String,
    /// Tool pattern (e.g., "samtools", "fastqc")
    pub tool_pattern: String,
    /// Request patterns to match (e.g., "sort bam", "quality check")
    pub request_patterns: Vec<String>,
    /// Template for generating args (supports {input}, {output} placeholders)
    pub args_template: String,
    /// Explanation template
    pub explanation_template: String,
    /// Confidence when this rule matches
    pub confidence: f32,
}

#[allow(dead_code)]
impl RuleCommandGenerator {
    /// Creates a new rule-based generator with default rules.
    pub fn new() -> Self {
        Self {
            rules: Self::default_rules(),
        }
    }

    /// Creates a generator with custom rules.
    pub fn with_rules(rules: Vec<CommandRule>) -> Self {
        Self { rules }
    }

    /// Default rules for common operations.
    fn default_rules() -> Vec<CommandRule> {
        vec![
            // samtools rules
            CommandRule {
                id: "samtools_sort".to_string(),
                tool_pattern: "samtools".to_string(),
                request_patterns: vec!["sort bam".to_string(), "sort by coordinate".to_string()],
                args_template: "sort -o {output}.bam {input}.bam".to_string(),
                explanation_template: "Sort BAM file by genomic coordinates".to_string(),
                confidence: 0.95,
            },
            CommandRule {
                id: "samtools_index".to_string(),
                tool_pattern: "samtools".to_string(),
                request_patterns: vec!["index bam".to_string(), "create bai".to_string()],
                args_template: "index {input}.bam".to_string(),
                explanation_template: "Create BAM index file (.bai)".to_string(),
                confidence: 0.95,
            },
            CommandRule {
                id: "samtools_flagstat".to_string(),
                tool_pattern: "samtools".to_string(),
                request_patterns: vec!["flagstat".to_string(), "alignment statistics".to_string()],
                args_template: "flagstat {input}.bam".to_string(),
                explanation_template: "Show alignment statistics".to_string(),
                confidence: 0.95,
            },
            // fastqc rules
            CommandRule {
                id: "fastqc_basic".to_string(),
                tool_pattern: "fastqc".to_string(),
                request_patterns: vec!["quality check".to_string(), "qc".to_string()],
                args_template: "{input}.fastq.gz".to_string(),
                explanation_template: "Run quality control on FASTQ files".to_string(),
                confidence: 0.90,
            },
            // bwa rules
            CommandRule {
                id: "bwa_index".to_string(),
                tool_pattern: "bwa".to_string(),
                request_patterns: vec!["index".to_string(), "build index".to_string()],
                args_template: "index {input}.fa".to_string(),
                explanation_template: "Build BWA index for reference genome".to_string(),
                confidence: 0.95,
            },
        ]
    }

    /// Checks if a rule matches the given tool and request.
    fn matches(&self, rule: &CommandRule, tool: &str, request: &str) -> bool {
        // Check tool pattern (exact match for now)
        if rule.tool_pattern != tool {
            return false;
        }

        // Check request patterns (case-insensitive substring match)
        // Use contains_ignore_case to avoid lowercase allocations
        rule.request_patterns
            .iter()
            .any(|p| contains_ignore_case(request, p))
    }

    /// Applies a rule to generate a command.
    fn apply(&self, rule: &CommandRule, request: &str) -> GeneratedCommand {
        // Try to extract file names from the request using common patterns.
        // Use iterator directly without intermediate Vec allocation
        let mut input_name = "input".to_string();
        let mut output_name = "output".to_string();
        let mut prev_word: Option<&str> = None;

        for word in request.split_whitespace() {
            // Use eq_ignore_ascii_case and contains checks without lowercase allocation
            let has_dot = word.contains('.');
            let is_flag = word.starts_with('-') || word.starts_with("--");
            // Detect file-like tokens (containing a dot extension)
            if has_dot && !is_flag {
                if input_name == "input" {
                    input_name = word.trim_end_matches([',', ';']).to_string();
                } else if output_name == "output" {
                    output_name = word.trim_end_matches([',', ';']).to_string();
                }
            }
            // Detect "to <file>" or "output <file>" patterns (case-insensitive)
            // Check if previous word was a keyword
            if let Some(prev) = prev_word {
                let was_keyword = prev.eq_ignore_ascii_case("to")
                    || prev.eq_ignore_ascii_case("output")
                    || prev.eq_ignore_ascii_case("into");
                if was_keyword && word.contains('.') {
                    output_name = word.trim_end_matches([',', ';']).to_string();
                }
            }
            prev_word = Some(word);
        }

        // Strip common extensions for placeholder substitution
        let strip_extensions = |name: &str| -> String {
            let mut s = name.to_string();
            // Strip compound extensions like .fastq.gz, .vcf.gz first
            for compound in &[".fastq.gz", ".fq.gz", ".vcf.gz", ".bed.gz", ".fa.gz"] {
                if s.ends_with(compound) {
                    s = s[..s.len() - compound.len()].to_string();
                    return s;
                }
            }
            // Then strip single extensions
            for ext in &[
                ".gz", ".bam", ".fastq", ".fa", ".fq", ".bed", ".vcf", ".sam", ".cram",
            ] {
                if s.ends_with(ext) {
                    s = s[..s.len() - ext.len()].to_string();
                    break;
                }
            }
            s
        };
        let input_base = strip_extensions(&input_name);
        let output_base = strip_extensions(&output_name);

        // Apply template with single-pass replacement to avoid intermediate Strings
        let args =
            if rule.args_template.contains("{input}") || rule.args_template.contains("{output}") {
                let mut result = String::with_capacity(
                    rule.args_template.len() + input_base.len() + output_base.len(),
                );
                let mut i = 0;
                let template = rule.args_template.as_str();
                while i < template.len() {
                    if template[i..].starts_with("{input}") {
                        result.push_str(&input_base);
                        i += 7;
                    } else if template[i..].starts_with("{output}") {
                        result.push_str(&output_base);
                        i += 8;
                    } else {
                        result.push(template[i..].chars().next().unwrap());
                        i += template[i..].chars().next().unwrap().len_utf8();
                    }
                }
                result
            } else {
                rule.args_template.clone()
            };

        GeneratedCommand {
            args,
            explanation: rule.explanation_template.clone(),
            confidence: rule.confidence,
            source: CommandSource::Rule {
                rule_id: rule.id.clone(),
            },
        }
    }
}

impl Default for RuleCommandGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl CommandGenerator for RuleCommandGenerator {
    async fn generate(
        &self,
        tool: &str,
        _docs: &str,
        _skill: Option<&Skill>,
        user_request: &str,
        _config: &Config,
    ) -> Result<GeneratedCommand> {
        // Find matching rule
        for rule in &self.rules {
            if self.matches(rule, tool, user_request) {
                return Ok(self.apply(rule, user_request));
            }
        }

        // No matching rule
        Err(crate::error::OxoError::LlmError(
            "No matching rule for this request".to_string(),
        ))
    }

    fn name(&self) -> &str {
        "rule"
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Composite Generator (Chain of Responsibility)
// ────────────────────────────────────────────────────────────────────────────

/// Composite generator that tries multiple generators in order.
///
/// This implements the chain of responsibility pattern, trying each
/// generator in sequence until one succeeds.
#[allow(dead_code)]
pub struct CompositeGenerator {
    generators: Vec<Box<dyn CommandGenerator>>,
}

#[allow(dead_code)]
impl CompositeGenerator {
    /// Creates a new composite generator with the given generators.
    pub fn new(generators: Vec<Box<dyn CommandGenerator>>) -> Self {
        Self { generators }
    }

    /// Creates a default composite with rule → LLM fallback.
    pub fn default_composite(client: LlmClient) -> Self {
        Self::new(vec![
            Box::new(RuleCommandGenerator::new()),
            Box::new(LlmCommandGenerator::new(client)),
        ])
    }
}

#[async_trait]
impl CommandGenerator for CompositeGenerator {
    async fn generate(
        &self,
        tool: &str,
        docs: &str,
        skill: Option<&Skill>,
        user_request: &str,
        config: &Config,
    ) -> Result<GeneratedCommand> {
        let mut last_error = None;

        for generator in &self.generators {
            match generator
                .generate(tool, docs, skill, user_request, config)
                .await
            {
                Ok(cmd) => {
                    tracing::debug!("Command generated by {}: {}", generator.name(), cmd.args);
                    return Ok(cmd);
                }
                Err(e) => {
                    tracing::trace!("Generator {} failed: {}, trying next", generator.name(), e);
                    last_error = Some(e);
                }
            }
        }

        // All generators failed
        Err(last_error.unwrap_or_else(|| {
            crate::error::OxoError::LlmError("All generators failed".to_string())
        }))
    }

    fn name(&self) -> &str {
        "composite"
    }
}

/// Check if haystack contains needle case-insensitively without allocation.
fn contains_ignore_case(haystack: &str, needle: &str) -> bool {
    if needle.is_empty() {
        return true;
    }
    if haystack.len() < needle.len() {
        return false;
    }

    let needle_chars: Vec<char> = needle.chars().collect();
    let mut haystack_iter = haystack.chars().peekable();

    while let Some(first) = haystack_iter.next() {
        if first.eq_ignore_ascii_case(&needle_chars[0]) {
            let mut matched = true;
            for needle_char in &needle_chars[1..] {
                match haystack_iter.peek() {
                    Some(h_char) if h_char.eq_ignore_ascii_case(needle_char) => {
                        haystack_iter.next();
                        continue;
                    }
                    _ => {
                        matched = false;
                        break;
                    }
                }
            }
            if matched {
                return true;
            }
        }
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_rule_generator_matches() {
        let generator = RuleCommandGenerator::new();

        // Should match
        assert!(generator.matches(
            &generator.rules[0],
            "samtools",
            "sort bam file by coordinate"
        ));

        // Should not match (wrong tool)
        assert!(!generator.matches(&generator.rules[0], "fastqc", "sort bam file"));

        // Should not match (wrong request)
        assert!(!generator.matches(&generator.rules[0], "samtools", "index bam file"));
    }

    #[test]
    fn test_rule_generator_apply() {
        let generator = RuleCommandGenerator::new();
        let cmd = generator.apply(&generator.rules[0], "sort bam file");

        assert_eq!(cmd.args, "sort -o output.bam input.bam");
        assert_eq!(cmd.explanation, "Sort BAM file by genomic coordinates");
        assert!(cmd.confidence > 0.9);
    }

    #[test]
    fn test_command_source_name() {
        let llm_source = CommandSource::Llm {
            model: "gpt-4".to_string(),
            cache_hit: false,
        };
        assert_eq!(llm_source.name(), "llm");

        let rule_source = CommandSource::Rule {
            rule_id: "test".to_string(),
        };
        assert_eq!(rule_source.name(), "rule");
    }
}
